/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Lab2_Festival
{
  public enum ConcertType
  {
    ROCK = 1,
    POP = 2,
    TECHNO = 3,
    HOUSE = 4,
  }
}
