/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Lab2_Festival
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class Ticket : TBase
  {
    private int _id;
    private int _concertId;
    private string _clientName;
    private string _buyDate;
    private int _numOfSeats;

    public int Id
    {
      get
      {
        return _id;
      }
      set
      {
        __isset.id = true;
        this._id = value;
      }
    }

    public int ConcertId
    {
      get
      {
        return _concertId;
      }
      set
      {
        __isset.concertId = true;
        this._concertId = value;
      }
    }

    public string ClientName
    {
      get
      {
        return _clientName;
      }
      set
      {
        __isset.clientName = true;
        this._clientName = value;
      }
    }

    public string BuyDate
    {
      get
      {
        return _buyDate;
      }
      set
      {
        __isset.buyDate = true;
        this._buyDate = value;
      }
    }

    public int NumOfSeats
    {
      get
      {
        return _numOfSeats;
      }
      set
      {
        __isset.numOfSeats = true;
        this._numOfSeats = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool id;
      public bool concertId;
      public bool clientName;
      public bool buyDate;
      public bool numOfSeats;
    }

    public Ticket() {
    }

    public Ticket(int id, int concertId, string clientName, string buyDate, int numOfSeats)
    {
        __isset.id = true;
        this._id = id;

        __isset.concertId = true;
        this._concertId = concertId;

        __isset.clientName = true;
        this._clientName = clientName;

        __isset.buyDate = true;
        this._buyDate = buyDate;

        __isset.numOfSeats = true;
        this._numOfSeats = numOfSeats;
    }

     public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32) {
                Id = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.I32) {
                ConcertId = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.String) {
                ClientName = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.String) {
                BuyDate = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 5:
              if (field.Type == TType.I32) {
                NumOfSeats = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("Ticket");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.id) {
          field.Name = "id";
          field.Type = TType.I32;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(Id);
          oprot.WriteFieldEnd();
        }
        if (__isset.concertId) {
          field.Name = "concertId";
          field.Type = TType.I32;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(ConcertId);
          oprot.WriteFieldEnd();
        }
        if (ClientName != null && __isset.clientName) {
          field.Name = "clientName";
          field.Type = TType.String;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(ClientName);
          oprot.WriteFieldEnd();
        }
        if (BuyDate != null && __isset.buyDate) {
          field.Name = "buyDate";
          field.Type = TType.String;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(BuyDate);
          oprot.WriteFieldEnd();
        }
        if (__isset.numOfSeats) {
          field.Name = "numOfSeats";
          field.Type = TType.I32;
          field.ID = 5;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(NumOfSeats);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("Ticket(");
      bool __first = true;
      if (__isset.id) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Id: ");
        __sb.Append(Id);
      }
      if (__isset.concertId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ConcertId: ");
        __sb.Append(ConcertId);
      }
      if (ClientName != null && __isset.clientName) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ClientName: ");
        __sb.Append(ClientName);
      }
      if (BuyDate != null && __isset.buyDate) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("BuyDate: ");
        __sb.Append(BuyDate);
      }
      if (__isset.numOfSeats) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("NumOfSeats: ");
        __sb.Append(NumOfSeats);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
