print("Pentru a adauga cost unui apartament la costul curent, tastati: adauga <nrAp> <sumaCost> <tipCost> <ziua>")
    print("Pentru a modifica costul unui apartament, tastati: modifica <nrAp> <sumaCost> tipCost> <ziua>")
    print("\nPentru a sterge costul unui apartament, tastati: sterge de la <nrAp> <ziua>")
    print("Pentru a sterge costul de la apartamentele dintr-un interval, tastati: sterge <start> , <stop>")
    print("Pentru a sterge un tip de cost de la toate apartamentele, tastati: sterge <tipCost> <ziua>")
    print("\nPentru a afisa toate apartamentele cu un cost mai mare decat unul dat, tastati: afiseaza > <suma>")
    print("Pentru a afisa un tip de cost de la toate apartamentele, tastati: afiseaza toate <tipCost>")
    print("Pentru a afisa costurile inainte de o zi si mai mari decat o suma, tastati: afiseaza < <ziua> > <suma>")
    print("\nPentru a afisa suma totala pentru un anumit tip, tastati: tipareste <tipCost>")
    print("Pentru a printa toate apartamentele sortat in functie de un cost, tastati: lista sortata <tipCost>")
    print("Pentru a printa costul total de la un apartament, tipariti: tipareste <nrAp>")