"""empty message

Revision ID: a81c761c92df
Revises: c91108c153ac
Create Date: 2019-06-18 09:42:45.821859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a81c761c92df'
down_revision = 'c91108c153ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('length', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word', 'length')
    # ### end Alembic commands ###
