"""empty message

Revision ID: cf47cebe3a92
Revises: 489a7c58eee1
Create Date: 2019-06-16 14:30:42.864652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf47cebe3a92'
down_revision = '489a7c58eee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admin_password', table_name='admin')
    op.drop_index('ix_admin_username', table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('password', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admin_username', 'admin', ['username'], unique=1)
    op.create_index('ix_admin_password', 'admin', ['password'], unique=1)
    # ### end Alembic commands ###
