def mesaje():        
    print("Apasati tasta 1 pentru a creea lista participantilor:")
    print("Apasati tasta 2 pentru a adauga la sfarsitul listei scorul unui participant:")
    print("Apasati tasta 3 pentru a insera scorul unui participant:")
    print("Apasati tasta 4 pentru a tipari lista in care participantii au scorul mai mic decat un scor dat:")
    print("Apasati tasta 5 pentru a tipari lista in care participantii sunt sortati:")
    print("Apasati tasta 6 pentru a tipari lista in care participantii au scorul mai mare decat un scor dat si sunt sortati:")        
    print("Apasati tasta 7 pentru a sterge scorul unui participant dat")
    print("Apasati tasta 8 pentru a sterge scorul unui interval dat de participanti")
    print("Apasati tasta 9 pentru a inlocui scorul unui participant")
    print("Tastati 10 pentru a tipari media unui interval dat de participanti")
    print("Tastati 11 pentru a tipari scorul minim dintr-un interval dat")
    print("Tastati 12 pentru a tipari participantii dintr-un interval care au scorul multiplu de 10")
    print("Tastati 13 pentru a filtra participantii care au scorul multiplul unui numar dat")
    print("Tastati 14 pentru a filtra participantii care au scorul mai mic decat un numar dat")
    print("Tastati 15 pentru a filtra participatii care au scorul un numar prim")
    print("Tastati 16 pentru a reface ultima operatie")
    print("Apasati tasta 17 pentru a tipari lista:")
    print("Apasati tasta 0 pentru a iesi din aplicatie:")